# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
      gym(scheme: 'AlertOnboarding', export_method: 'app-store')
    build_app(scheme: "AlertOnboarding")
increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "AlertOnboarding.xcodeproj"
  )
    upload_to_testflight
  end
lane :metrics do
    scan(scheme: "AlertOnboarding", code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: true, scheme: "AlertOnboarding", build_directory: "./DerivedData", output_directory: "./reports", proj: "./AlertOnboarding.xcodeproj")
    sh("cd .. && lizard ./[SOURCE_FOLDER] -l swift --xml > ./reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    sonar
end
end
