# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
#    enable_automatic_code_signing(path: "AlertOnboarding.xcodeproj")
#      gym(scheme: 'AlertOnboarding', export_method: 'app-store')
   # build_app(scheme: "AlertOnboarding")
#increment_build_number(
#    build_number: latest_testflight_build_number + 1,
 #   xcodeproj: "AlertOnboarding.xcodeproj"
  #)
   # ...
 build_app
  cert
 sigh(force: true)
  crashlytics(emails: "productscog@gmail.com”,
api_token: "6baee5125152c8e8f9b7dfa6c862a10005578358",
              build_secret: "4b1b1bd7cdf9bfbca6c0e2b2433f5e18461f9f4933526f45153ebf762ff69cbe")


    # upload_to_testflight(changelog: "Add rocket emoji")
   #  upload_to_testflight(skip_waiting_for_build_processing: true)
  end
lane :metrics do
    scan(scheme: "AlertOnboarding", code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: true, scheme: "AlertOnboarding", build_directory: "./DerivedData", output_directory: "./reports", proj: "./AlertOnboarding.xcodeproj")
    sh("cd .. && lizard ./[SOURCE_FOLDER] -l swift --xml > ./reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    sonar
end
end
